openapi: 3.0.3
info:
  title: Authorization server
  description: Authorization server for the project 'Livestock shop'.
  contact:
    name: Luke Sukhanov
    email: lukesukhanov@gmail.com
    url: https://github.com/lukesukhanov
  version: '1.0'
servers:
- url: http://127.0.0.1:9000
paths:
  /users:
    post:
      tags:
      - Users
      summary: Saves a new user
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserForm'
      responses:
        200:
          description: Normal response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserId'
        400:
          description: Response in case of invalid request parameters
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/InvalidRequestParametersProblem'
components:
  schemas:
    UserForm:
      type: object
      properties:
        email:
          type: string
          example: vasya@gmail.com
        password:
          type: string
          example: vasya123
    UserId:
      type: object
      properties:
        userId:
          type: integer
          format: int64
          example: 1
    InvalidRequestParametersProblem:
      type: object
      properties:
        type:
          type: string
          example: /probs/invalidRequestParameters
        title:
          type: string
          example: Invalid request parameters
        status:
          type: integer
          format: int32
          example: 400
        invalid-params:
          type: array
          items:
            $ref: '#/components/schemas/InvalidRequestParameter'
    InvalidRequestParameter:
      type: object
      properties:
        name:
          type: string
          example: email
        reason:
          type: string
          example: Email is required